package day02_test

import "testing"

func TestOne(t *testing.T) {
	countedTwo := 0
	countedThree := 0
	for _, id := range input {
		matches := make(map[rune]int)
		for _, b := range id {
			matches[b] = matches[b] + 1
		}
		foundTwo := false
		foundThree := false
		for _, m := range matches {
			if m == 2 {
				foundTwo = true
			}
			if m == 3 {
				foundThree = true
			}
		}
		if foundTwo {
			countedTwo += 1
		}
		if foundThree {
			countedThree += 1
		}
	}

	t.Error(countedThree * countedTwo)
}
func TestTwo(t *testing.T) {
	possiblePositions := len(input[0])
	maps := make([]map[string]struct{}, possiblePositions)
	for index := 0; index < possiblePositions; index++ {
		maps[index] = make(map[string]struct{})
	}
	for _, id := range input {
		for i := range id {
			str := id[:i] + id[i+1:]
			if _, ok := maps[i][str]; ok {
				t.Fatal("found", str, id[:i], "*", id[i+1:], id)
			}
			maps[i][str] = struct{}{}
		}
	}
}

var inputTest = []string{
	"abcdef",
	"bababc",
	"abbcde",
	"abcccd",
	"aabcdd",
	"abcdee",
	"ababab",
}

var input = []string{
	"rvefnvyxzbodgpnpkumawhijsc",
	"rvefqtyxzsddglnppumawhijsc",
	"rvefqtywzbodglnkkubawhijsc",
	"rvefqpyxzbozglnpkumawhiqsc",
	"rvefqtyxzbotgenpkuyawhijsc",
	"rvefqtyxzbodglnlkumtphijsc",
	"rwefqtykzbodglnpkumawhijss",
	"rvynqtyxzbodglnpkumawrijsc",
	"rvefqtyxlbodgcnpkumawhijec",
	"rvefqtyxzbodmlnpnumawhijsx",
	"rvefqtyxzbqdbdnpkumawhijsc",
	"rvefqtyxzlodblnpkuiawhijsc",
	"rvefqtyizrodelnpkumawhijsc",
	"rveffjyxzgodglnpkumawhijsc",
	"rvefqjyxzbodalnpkumadhijsc",
	"rvefqtidzbodglnpkumawhdjsc",
	"hvefqtygzbodglnpkumawhijfc",
	"rzefqtyxzbodglfhkumawhijsc",
	"rmefqtyxzbolglnpkumaehijsc",
	"rnefqqyxzbodglnhkumawhijsc",
	"rvwfqvyxzbodglnpcumawhijsc",
	"rvefqtyxzbokgltpkumavhijsc",
	"rvefciyxzbodglnmkumawhijsc",
	"rvefptyxzbodglnpkuhashijsc",
	"rvefqtyxzrodglnpkxmawhiqsc",
	"rvefqtyxzbotglnpkumawriwsc",
	"rvufqtyxzbodglnplumawhijvc",
	"rvefutykzbodglnpkumaahijsc",
	"rvefqtyxqbodgllprumawhijsc",
	"rvegqttxzbodgllpkumawhijsc",
	"dvefqtyxzsodglnpkumawdijsc",
	"rvefqtyxkbodglnfkumawhijsj",
	"rvefqtyxzbodnlnpcumawhijnc",
	"rvefqtyxzbodglfpkuocwhijsc",
	"rvecqtyxzbbdganpkumawhijsc",
	"rvefytyxzbodglnpkubgwhijsc",
	"rvefxtyazbomglnpkumawhijsc",
	"rvefqgyxzbodglnpkumawyiksc",
	"avefqtyxzbodglnfkummwhijsc",
	"fvefqtyxzbbdglnpkumswhijsc",
	"rvefqtyxzxodglnpkumuuhijsc",
	"rvezqtyxzbydclnpkumawhijsc",
	"rvefqtyxzbohglnpkumawdijjc",
	"rvejqtyxzbodrlnpkumawhijsd",
	"rvefitzxzbxdglnpkumawhijsc",
	"rvefutyxzbvdglnikumawhijsc",
	"rvefqtyazbodgqnbkumawhijsc",
	"rvefqtyxzbolglnpkwmajhijsc",
	"rvefqtyxzjodglnpgwmawhijsc",
	"rvefhtyxzbodglbpaumawhijsc",
	"mvexqtyxzbodglnpkumawrijsc",
	"rvefqtyxwbodglnpkumawhbxsc",
	"rvefqtyxzbodgsnpkudawsijsc",
	"rvwfqtyxzbonglnwkumawhijsc",
	"rvefqtyxzjodglnpkfmawhwjsc",
	"rvefqtyxzbodglntkumughijsc",
	"rvefctyxzbodglnpkumawhiwsx",
	"avefqtyvzbodglnpkumawhijsb",
	"rfefqtyxzlodglnphumawhijsc",
	"rvefqtyxzfowglnpkumaehijsc",
	"rvhfvtyxzbodgqnpkumawhijsc",
	"rfefqtyxzbodglapkumuwhijsc",
	"rvefqclxzbodglnzkumawhijsc",
	"qvefqtyxzbodglnckumcwhijsc",
	"rvefqtyxzkodglnpkymawgijsc",
	"rvefqtyxzbodgfnpkumafhizsc",
	"rvefqtyxzbodglnxkumavhijsf",
	"rvevqtyxzbodgpnpkurawhijsc",
	"rvefqtyxziodglnpkubawhijss",
	"rrefqtpxzyodglnpkumawhijsc",
	"rvefqfyxzbodglcpkxmawhijsc",
	"rvefdtyxzbodglnpkumvwhijsn",
	"rverqtyxzbodglnpkwmawhijuc",
	"rvecjtyxzboxglnpkumawhijsc",
	"rvefqtyxzbodglnpkqmaxhifsc",
	"rtnfqtyxzbodglnpkumawhijmc",
	"lvefqtyxzbodelnpkumawhijsz",
	"dvefqtyxzbbdgvnpkumawhijsc",
	"rvefqlyhzbodglnpkumtwhijsc",
	"roefqtyxlbodglnpkumawhyjsc",
	"rvefqsydzjodglnpkumawhijsc",
	"rveybtyxzbodglnpkumawhijsn",
	"rvefqtyhzbodgvnpmumawhijsc",
	"rvefqxyazboddlnpkumawhijsc",
	"vvefqtyxzbohglqpkumawhijsc",
	"reefhtyxzbodglnpkkmawhijsc",
	"rvefqtyxzbodglnpkulowhijrc",
	"rveqqtyxzbodgknpkumawhijsk",
	"jvefqtqxzbodglnpkumawiijsc",
	"rvefqtyxzboxglnpvuqawhijsc",
	"rvefquyxzbodglwwkumawhijsc",
	"rvefqtyxzbodnlnpkumawhgjbc",
	"rvdfqthxdbodglnpkumawhijsc",
	"rvefqtyxzbodllnpkumawhujsb",
	"evefqtyxzboyglnpkumowhijsc",
	"rvefktyxzbomglnpzumawhijsc",
	"rvefqtyxzbodhlnnkrmawhijsc",
	"rvefqtyxrbodglnpkujaehijsc",
	"rvefqtyzzbodglnpkumrwhijsb",
	"evefqtyxzpodglfpkumawhijsc",
	"rvefqtyxibodglkpyumawhijsc",
	"rrefqtyxzbodglnpkudawhajsc",
	"rvifqtyxzbodglxpkumawhijlc",
	"rxefqtyxzbedglnpkumawhijsp",
	"rvnfqtyxzbopglnpkuqawhijsc",
	"rvefqtyxkbodglnpoumawoijsc",
	"dvefwtyxzbodglnpksmawhijsc",
	"rvkfqtyxzbodglnpkdmawhijsa",
	"rcefytyxzzodglnpkumawhijsc",
	"rvefqtkxzbodglnpktqawhijsc",
	"nvezqhyxzbodglnpkumawhijsc",
	"rrefqtyxzbodgunpkumpwhijsc",
	"rvefqtaxzbodgknpkumawhijic",
	"pvefqtyxzbodglnpkuxawsijsc",
	"rvefqtyxzbodglkpvumawhjjsc",
	"wvefqtyxzkodglnpkumawhhjsc",
	"rzefqtyxzbotglnpkumawhxjsc",
	"rvefqtxpzbodglnpkumawzijsc",
	"bgefqtyxzbodglnpkrmawhijsc",
	"rvefqlyxzbodglnpkumilhijsc",
	"cbefqtyxzbodglnpkumawhiesc",
	"rvefqtyxzbydelnpkumahhijsc",
	"rvefntyxzbodglnpkumaehijsw",
	"rverqtyxztodglopkumawhijsc",
	"rvefqtyxzdodgwrpkumawhijsc",
	"rvefqtyxibodglnikumawhtjsc",
	"qvafqtyxzbodglnpkurawhijsc",
	"rvefqtyxwbodglnpaumawoijsc",
	"rvefqtyxzoodglndknmawhijsc",
	"rvdfqtlxzyodglnpkumawhijsc",
	"rvefqtyxzbodglngfumawhinsc",
	"rsefqtyxzbodglnpkumawhijek",
	"rvoestyxzbodglnpkumawhijsc",
	"svefqtyxzboaglnprumawhijsc",
	"rvefqtybzbodgwnpkumawwijsc",
	"rvefqtyxzdwdglnpkvmawhijsc",
	"rvlfqtyxzbodglnpkrmawhixsc",
	"rvefqtyxwbodglepkumawhijsd",
	"rvefqtbxzbodglnqkumawhijmc",
	"rvefqtzxzbodglnpkumuzhijsc",
	"rvefqtyxzbodglnpkumawzwnsc",
	"rvwfqtyxzboiglnpkumawhijsg",
	"rtehotyxzbodglnpkudawhijsc",
	"rvegqtyxzbodglnpyumawhijsl",
	"rvecqtyxzbsdglnpkumawhojsc",
	"rvefqtyxzbodmlnpkumaghijfc",
	"rvefqtyxzxodglnpkumanvijsc",
	"rvefqtyxzbodglnbiugawhijsc",
	"lvefqtlxzbodglnplumawhijsc",
	"rvefqtyxvbodglnpkumaldijsc",
	"rmefqtyxzbodgvnpkuuawhijsc",
	"rvefqtyxzbodglnpkymeuhijsc",
	"rvefqtyxzuodganpsumawhijsc",
	"rxefqtyxzbodglnpkumgwhijwc",
	"rvefgtyxzbodglnpkudawxijsc",
	"ahefqtyxzbodglnpkumawhejsc",
	"rfefqtyxzbzdglnpkusawhijsc",
	"rvefqtyszqodgljpkumawhijsc",
	"rvefqtylzboiglnpkumrwhijsc",
	"rvefqtyxzltdglnpkumawhijsu",
	"rbefqtyxzbodglnpqumawhijsi",
	"rvefqtyozpodglnpkumawhijsa",
	"zvefqtyxzpopglnpkumawhijsc",
	"rvefqtyxzbodglnfkqmawhijsp",
	"rvefqtyxzbodgliakumawhijsf",
	"rvefqtymzrodgfnpkumawhijsc",
	"ivejqtyxzbodglnpkumawhijuc",
	"rvefqtyxzbodflnpkxwawhijsc",
	"dvrfqtyxzbodglnpkumashijsc",
	"rqefqtyxzbwdglnpkumawvijsc",
	"tvefqtkxzbodgltpkumawhijsc",
	"rvefdtyxzbodguxpkumawhijsc",
	"rveqqtyxvbodglnykumawhijsc",
	"rvefqtypzcovglnpkumawhijsc",
	"rvefqnyxzbosglnpkumdwhijsc",
	"rvefstjxzbodslnpkumawhijsc",
	"rvefqzyxzpodglnpkummwhijsc",
	"rvefqkyxzbodglnhgumawhijsc",
	"rvufqvyxzbodklnpkumawhijsc",
	"rvefotyxzhodglnpkumawhijsk",
	"rvefqtyxzbokglnpkumawvcjsc",
	"lvefqtyxzbolglnpkumawoijsc",
	"rvefqtywzoodglfpkumawhijsc",
	"rvehqtqxzbodglnpkumawhcjsc",
	"rqefqtyxzbodolnpkumjwhijsc",
	"rvefqtyxzbodglrpkunawgijsc",
	"rvefqtyxzbodglamkumawdijsc",
	"rvefvtyzzbodllnpkumawhijsc",
	"rvefqtyxzbldglnpfcmawhijsc",
	"rvefppyxzbodglnpkucawhijsc",
	"rvefquyuzbodglnpkumkwhijsc",
	"rvefqtyxzbodgqxpkumawhivsc",
	"rtefotyxzbodglnpkudawhijsc",
	"rvefqtyxzbodgbnmkuzawhijsc",
	"ivefqtyxzbodgsnpkumzwhijsc",
	"rvhfqtyxzbodolnpkumawhijsz",
	"rvefvtyxzbodwlnpkusawhijsc",
	"riemqtyxzbodglnpkumawhiasc",
	"rvtfqtyxzbqdglnpkumawuijsc",
	"raesqtyxzbodglnpkumawhijsj",
	"rvefqtyxzbodalmpkumawhihsc",
	"rvefqtlxzbodgznpkkmawhijsc",
	"rvefqbyxzbodglgpkubawhijsc",
	"rvefqtyxnbodgxnpkumswhijsc",
	"rvefqtyxzkodvlnukumawhijsc",
	"rvefqtyzzbocglnpkumafhijsc",
	"rvhfqtyxzbodglmpkumgwhijsc",
	"rvsfrtyxzbodnlnpkumawhijsc",
	"rvefqtyxzbxdglnpkujcwhijsc",
	"rvefqtyvzrodglnphumawhijsc",
	"reetatyxzbodglnpkumawhijsc",
	"rvefqtyxzbodglnpzumaoqijsc",
	"ovefqtyyzbodglnvkumawhijsc",
	"rvefqbyxzbodnlnpkumawhijsi",
	"xvefqtyxzbodgrnpkumawrijsc",
	"rvebqtyxzbodglnpkumazhiasc",
	"rqeretyxzbodglnpkumawhijsc",
	"rvefqtyxzyodglapkumvwhijsc",
	"rvesqxyxzbodglnpvumawhijsc",
	"rvefqtyxeborglnpkufawhijsc",
	"rvecqtyxzbodflnpkumawnijsc",
	"rvefdpyxtbodglnpkumawhijsc",
	"rvefqtyfzbodclnpkymawhijsc",
	"rvefqtywzbodglnpxumawhiusc",
	"rvefqtyxzbodglnpkumawzbjwc",
	"rvewqtyxdbodglnpxumawhijsc",
	"rvefqtyxzgocglnpkgmawhijsc",
	"rvufqtyxzbodggnpkuzawhijsc",
	"rvefqtynzlodgllpkumawhijsc",
	"rvedqtyxzbodghnpkumawhujsc",
	"rvefqtyxlbodgnnpkpmawhijsc",
	"rvefqtyxzboqglnpkzmawhijec",
	"rvefqtyxzbodglnpkfmwwyijsc",
	"rwefqtkxzbodzlnpkumawhijsc",
	"rvefqtyxvbodglnpkufawhyjsc",
	"rvefqtyxzbodgltpkumawhqmsc",
	"rvefctyxzbodglfpkumathijsc",
	"rvefqtyxzbodgfnpkuuawhijfc",
	"rvefqttxzbodglnpmumawhijwc",
	"rvefqtyxzbodglnpkqmawhihsj",
	"rvefqtyxzbsdglcnkumawhijsc",
	"rvbiqtyxzbodglnpkumawhijlc",
	"rnefqtylzvodglnpkumawhijsc",
	"mvefqtyxzbddglnpkumcwhijsc",
	"rvefwtyxzbodglnpkgmawhijxc",
	"rvefqtyxljodglnpkumxwhijsc",
	"rvefqtyxzbodglnpkuprwhijsd",
	"rcxfqtyxzbldglnpkumawhijsc",
	"rvetqtyxzbojglnpkumewhijsc",
	"rvxfqtyxzbtdglnpkbmawhijsc",
}
